# Generated by Django 4.2.25 on 2025-10-08 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_targets', '0029_alter_basetarget_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='tom_targets.basetarget')),
            ],
        ),
    ]
