{{- if and (not .Values.database.host) .Values.cnpg.superuser.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tom-demo.fullname" . }}-cnpg-superuser
type: Opaque
stringData:
  # CloudNativePG expects the "password" key for superuserSecret
  password: {{ .Values.cnpg.superuser.password | quote }}
{{- end }}

{{- if and (not .Values.database.host) .Values.database.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tom-demo.fullname" . }}-cnpg-app
type: Opaque
stringData:
  # Referenced in bootstrap.initdb.secret.key
  password: {{ .Values.database.password | quote }}
{{- end }}
