apiVersion: v1
kind: Service
metadata:
  name: {{ include "tom-deploy.fullname" . }}
  labels:
    {{- include "tom-deploy.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "tom-deploy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "backend"
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
